### ISSUE TITLE
unittest BugCheck 1a

### ISSUE THREAD

**Issue by nil-ref** [MiroKaku/libwsk#1]
MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 0000000000061948, The subtype of the BugCheck.
Arg2: 0000000118c05806
Arg3: 0000000000000001
Arg4: 0000000118c05806

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1749

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 30083

    Key  : Analysis.Init.CPU.mSec
    Value: 4702

    Key  : Analysis.Init.Elapsed.mSec
    Value: 306851

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 63

    Key  : WER.OS.Branch
    Value: rs2_release

    Key  : WER.OS.Timestamp
    Value: 2017-03-17T18:34:00Z

    Key  : WER.OS.Version
    Value: 10.0.15063.0

BUGCHECK_CODE:  1a

BUGCHECK_P1: 61948

BUGCHECK_P2: 118c05806

BUGCHECK_P3: 1

BUGCHECK_P4: 118c05806

PROCESS_NAME:  System

STACK_TEXT:  
ffffba01`731e6d08 fffff801`11405322     : 00000000`00061948 00000000`0000001a ffffba01`731e6e70 fffff801`112b7c60 : nt!DbgBreakPointWithStatus
ffffba01`731e6d10 fffff801`11404bd2     : 00000000`00000003 ffffba01`731e6e70 fffff801`114b6180 00000000`0000001a : nt!KiBugCheckDebugBreak+0x12
ffffba01`731e6d70 fffff801`11374417     : 00000000`00000000 fffff801`1121cfd6 00000000`00000000 ffffd009`00000000 : nt!KeBugCheck2+0x922
ffffba01`731e7480 fffff801`113b8774     : 00000000`0000001a 00000000`00061948 00000001`18c05806 00000000`00000001 : nt!KeBugCheckEx+0x107
ffffba01`731e74c0 fffff801`113907c5     : 00000000`00000000 00000000`00000000 00000000`00000001 00000000`00000001 : nt!MiDereferenceIoPages+0xeff80
ffffba01`731e7570 fffff800`bedf6a06     : 00000000`00000000 00000000`00000000 00000000`00000000 ffffd009`b080c000 : nt!MmUnlockPages+0x164325
ffffba01`731e7650 fffff800`bedf463b     : ffffd009`b14586a0 ffffba01`731e7760 ffffd009`b080c000 00000000`00000000 : unittest!WSKUnlockBuffer+0x66 [D:\test\libwsk\src\libwsk.cpp @ 163] 
ffffba01`731e7680 fffff800`bedf497d     : ffffd009`b1458670 ffffba01`00000000 ffffba01`00000000 00000000`00000000 : unittest!WSKFreeContextIRP+0x3b [D:\test\libwsk\src\libwsk.cpp @ 187] 
ffffba01`731e76b0 fffff800`bedf1c07     : 00000000`00000000 fffff800`bedf72b0 fffff800`00000000 00000000`00000000 : unittest!WSKGetAddrInfo+0x30d [D:\test\libwsk\src\libwsk.cpp @ 1630] 
ffffba01`731e7790 fffff800`bedf2b7b     : 00000000`00000000 fffff800`bedf72b0 00020019`00000002 fffff800`bedf0002 : unittest!UnitTest::StartWSKServer+0x197 [D:\test\libwsk\test\main.cpp @ 292] 
ffffba01`731e78b0 fffff800`bedf2e1b     : ffffd009`b1606590 ffffd009`b080c000 ffffd009`b080c000 ffffd009`b1606590 : unittest!DriverEntry+0x6b [D:\test\libwsk\test\main.cpp @ 49] 
ffffba01`731e78f0 fffff800`bedf2d50     : ffffd009`b080c000 ffffba01`731e7a60 ffffd009`b1606590 ffffd009`b1606590 : unittest!FxDriverEntryWorker+0xbf [minkernel\wdf\framework\kmdf\src\dynamic\stub\stub.cpp @ 349] 
ffffba01`731e7930 fffff801`1163c606     : 00000000`00000000 00000000`00000000 ffffd009`b1606590 00000000`00000000 : unittest!FxDriverEntry+0x20 [minkernel\wdf\framework\kmdf\src\dynamic\stub\stub.cpp @ 238] 
ffffba01`731e7960 fffff801`1172df37     : fffff801`11600200 00000000`00000000 00000000`00000000 fffff801`11600380 : nt!IopLoadDriver+0x522
ffffba01`731e7b40 fffff801`112271c8     : 00000000`00000000 ffffffff`80001d78 fffff801`00000000 ffffd009`b0f3d040 : nt!IopLoadUnloadDriver+0x57
ffffba01`731e7b80 fffff801`112c1a37     : 00000000`00000000 00000000`00000080 ffffd009`af063680 ffffd009`b0f3d040 : nt!ExpWorkerThread+0xd8
ffffba01`731e7c10 fffff801`11379796     : ffffba01`71e55180 ffffd009`b0f3d040 fffff801`112c19f0 00000000`00000246 : nt!PspSystemThreadStartup+0x47
ffffba01`731e7c60 00000000`00000000     : ffffba01`731e8000 ffffba01`731e2000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x16

FAULTING_SOURCE_LINE:  D:\test\libwsk\src\libwsk.cpp

FAULTING_SOURCE_FILE:  D:\test\libwsk\src\libwsk.cpp

FAULTING_SOURCE_LINE_NUMBER:  163

FAULTING_SOURCE_CODE:  
   159:             {
   160:                 MmUnlockPages(WSKBuffer->Mdl);
   161:             }
   162: 
>  163:             IoFreeMdl(WSKBuffer->Mdl);
   164:             WSKBuffer->Mdl = nullptr;
   165:         }
   166:     }
   167: }
   168: 

SYMBOL_NAME:  unittest!WSKUnlockBuffer+66

MODULE_NAME: unittest

IMAGE_NAME:  unittest.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  66

FAILURE_BUCKET_ID:  0x1a_61948_unittest!WSKUnlockBuffer

OS_VERSION:  10.0.15063.0

BUILDLAB_STR:  rs2_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

**Comment by MiroKaku** [comment]
Need a dump.

**Comment by luciouskami** [comment]
how to reproduce?Could you afford the step.
