### ISSUE TITLE
berkeley.cpp [BUG]

### ISSUE THREAD

**Issue by nil-ref** [MiroKaku/libwsk#3]
berkeley.cpp: 82: SOCKET WSKAPI accept

return WSKSetLastError(Status), (!NT_SUCCESS(Status) ? SOCKET_ERROR : SOCKET_SUCCESS);
 =>
return WSKSetLastError(Status), Socket;

**Comment by nil-ref** [comment]
berkeley.cpp: 19: SOCKET WSKAPI socket

When protocol is 0.
+++
    if (!protocol){
        switch (type){
            case SOCK_DGRAM:    protocol = IPPROTO_UDP;    break;
            case SOCK_STREAM:   protocol = IPPROTO_TCP;    break;
            }
        }

**Comment by MeeSong** [comment]
Thanks, it's fixed.
